#!/usr/bin/env python3
"""
Converte i frame idle1.png e idle2.png di un personaggio in un header C
con array RGB565 pronti per LovyanGFX su ESP32-S3.

Uso: python convert_to_h.py <nome_personaggio>
Es.: python convert_to_h.py Drowsea

Output: processed/<nome>/<nome>_idle.h
"""

import sys, os
import numpy as np
from PIL import Image

SPRITE_DIR = os.path.dirname(os.path.abspath(__file__))

def to_rgb565(img: Image.Image) -> np.ndarray:
    """RGBA → RGB565 uint16, trasparente = 0x0000."""
    arr = np.array(img.convert('RGBA'), dtype=np.uint32)
    r, g, b, a = arr[:,:,0], arr[:,:,1], arr[:,:,2], arr[:,:,3]
    # Pixel con alpha < 128 → colore trasparente = 0x0000
    rgb565 = ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)
    rgb565[a < 128] = 0x0000
    # Evita 0x0000 per pixel opachi neri (rarissimo ma corretto)
    black_opaque = (rgb565 == 0) & (a >= 128)
    rgb565[black_opaque] = 0x0001
    return rgb565.astype(np.uint16)

def write_header(name: str):
    proc_dir = os.path.join(SPRITE_DIR, "processed", name)
    out_path  = os.path.join(proc_dir, f"{name.lower()}_idle.h")

    guard = f"{name.upper()}_IDLE_H"
    lines = [
        f"#pragma once",
        f"// Auto-generated by convert_to_h.py — {name} idle frames",
        f"// Formato: RGB565, trasparente = 0x0000",
        f"#include <stdint.h>",
        f"",
    ]

    all_frames = [
        "idle1","idle2","angry1","angry2",
        "happy1","happy2","sick1","sick2","sleep1","sleep2"
    ]

    sizes = []
    for frame in all_frames:
        path = os.path.join(proc_dir, f"{frame}.png")
        if not os.path.exists(path):
            print(f"  ERRORE: {path} non trovato")
            sys.exit(1)

        img  = Image.open(path)
        w, h = img.size
        sizes.append((w, h))
        data = to_rgb565(img).flatten()
        n    = len(data)

        print(f"  {frame}: {w}×{h}  ({n} pixel)")

        lines.append(f"// {name} — {frame}: {w}×{h} px")
        lines.append(f"static const uint16_t {name.lower()}_{frame}[{n}] PROGMEM = {{")
        for i in range(0, n, 12):
            chunk = data[i:i+12]
            lines.append("    " + ", ".join(f"0x{v:04X}" for v in chunk) + ",")
        lines.append("};")
        lines.append("")

    # Dimensioni
    for frame, (w, h) in zip(all_frames, sizes):
        lines.append(f"static const int16_t {name.upper()}_{frame.upper()}_W = {w};")
        lines.append(f"static const int16_t {name.upper()}_{frame.upper()}_H = {h};")

    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")

    print(f"  → {out_path}")

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Uso: python convert_to_h.py <Nome>")
        sys.exit(1)
    name = sys.argv[1]
    print(f"Conversione {name}...")
    write_header(name)
    print("Fatto.")
